/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113547-ga42f884cd2-20240206"
#endif /* AVUTIL_FFVERSION_H */
